#############################
#        TO FILL            #
#############################

# The title that appears on the tab
title: Tyler Thomas | Photographer | Programmer | Person
# The title on the web page
full_name: Tyler Thomas
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS
# Int: Spacing between each photo
spacing: 0
# Boolean(true|false): Shuffle the photos in the album
shuffle: false
# Int: Number of columns for square or columns
columns: 2
# Int: Max height for rows
max_height: 777
# Handle
instagram: tylerlovesapples

######################
# END OF CONFIG CODE #
#  Ignore below :)   #
######################
#
# Name of your gallery (this will show up at the top of your page and in the RSS feed)
name: Tyler's Gallery
# Short description (goes below the title; it will also be used in the RSS feed)
description: Photography Portfolio
# Your name, as you want it to appear underneath each post and in the footer
author: Tyler Thomas
# Your email if you want it to be linked on the contact page
author_email: tylert@southern.edu
# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /
# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: http://localhost:5500/
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://tylerthomas.xyz
